name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: nicolaskivimaki
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Flask
      run: pip install flask
    - name: install Flask dependencies
      run: pip install -r requirements.txt
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Install Robot Framework
      run: pip install robotframework-seleniumlibrary
    - name: Install flask_sql_alchemy
      run: pip install flask_sqlalchemy
    - name: Launch Flask App
      run: |
        cd src
        flask run
    - name: Run tests
      run: python3 -m pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Configure chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Run Robot Framework
      run: poetry run invoke robot
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
        FLASK_ENV: development
        