
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Flask
        run: pip install flask
      - name: Install poetry 
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install Robot Framework
        run: pip install robotframework
      - name: Run Robot Framework
        run: poetry run invoke robot


